# Generated by Django 3.2.6 on 2021-09-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default='', max_length=200, verbose_name='Идентификатор места'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='title_short',
            field=models.CharField(default='', max_length=200, verbose_name='Краткий заголовок'),
            preserve_default=False,
        ),
    ]
