# Generated by Django 3.2.6 on 2021-10-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(db_index=True, verbose_name='Порядок следования'),
        ),
    ]
