# Generated by Django 3.2.6 on 2021-10-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20211011_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Заголовок'),
        ),
    ]
